// <auto-generated />
using System;
<<<<<<< HEAD
using MCBA_Admin.Data;
=======
using MCBA_Web.Data;
>>>>>>> dev
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

<<<<<<< HEAD
namespace MCBAAdmin.Migrations
{
    [DbContext(typeof(MCBAContext))]
<<<<<<<< HEAD:Admin Web-API/Migrations/20230118054557_Models.Designer.cs
    [Migration("20230118054557_Models")]
========
    [Migration("20230120212116_Models")]
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
    partial class Models
=======
namespace MCBAWeb.Migrations
{
    [DbContext(typeof(MCBAContext))]
<<<<<<<< HEAD:Customer Web/Migrations/20230120215445_Models-Update.Designer.cs
<<<<<<<< HEAD:Customer Web/Migrations/20230122005306_Models.Designer.cs
    [Migration("20230122005306_Models")]
    partial class Models
========
    [Migration("20230120215445_Models-Update")]
    partial class ModelsUpdate
>>>>>>>> dev:Customer Web/Migrations/20230120215445_Models-Update.Designer.cs
========
    [Migration("20230120212116_Models")]
    partial class Models
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
>>>>>>> dev
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Account", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Account", b =>
>>>>>>> dev
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1000");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("AccountNumber");

                    b.HasIndex("CustomerID");

                    b.ToTable("Account");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Address", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Address", b =>
>>>>>>> dev
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("Address");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.BillPay", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.BillPay", b =>
>>>>>>> dev
                {
                    b.Property<int>("BillPayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillPayID"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("PayeeID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduleTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("BillPayID");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("PayeeID");

                    b.ToTable("BillPay");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Customer", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Customer", b =>
>>>>>>> dev
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1000");

                    b.Property<bool>("HasDefaultProfilePicture")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePictureContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TFN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Login", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Login", b =>
>>>>>>> dev
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("10000000");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Login");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Payee", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Payee", b =>
>>>>>>> dev
                {
                    b.Property<int>("PayeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayeeID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
<<<<<<< HEAD
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");
=======
<<<<<<<< HEAD:Customer Web/Migrations/20230120215445_Models-Update.Designer.cs
<<<<<<<< HEAD:Customer Web/Migrations/20230122005306_Models.Designer.cs
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
========
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");
>>>>>>>> dev:Customer Web/Migrations/20230120215445_Models-Update.Designer.cs
========
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
>>>>>>> dev

                    b.HasKey("PayeeID");

                    b.ToTable("Payee");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Transaction", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Transaction", b =>
>>>>>>> dev
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<string>("Comment")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("DestinationAccountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("TransactionID");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("DestinationAccountNumber");

                    b.ToTable("Transaction");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Account", b =>
                {
                    b.HasOne("MCBA_Admin.Models.Customer", "Customer")
=======
            modelBuilder.Entity("MCBA_Web.Models.Account", b =>
                {
                    b.HasOne("MCBA_Web.Models.Customer", "Customer")
>>>>>>> dev
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Address", b =>
                {
<<<<<<<< HEAD:Admin Web-API/Migrations/20230118054557_Models.Designer.cs
                    b.HasOne("MCBA_Admin.Models.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("MCBA_Admin.Models.Address", "CustomerID")
========
                    b.HasOne("MCBA_Web.Models.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("MCBA_Web.Models.Address", "CustomerID")
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
=======
            modelBuilder.Entity("MCBA_Web.Models.Address", b =>
                {
                    b.HasOne("MCBA_Web.Models.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("MCBA_Web.Models.Address", "CustomerID")
>>>>>>> dev
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.BillPay", b =>
                {
                    b.HasOne("MCBA_Admin.Models.Account", "Account")
=======
            modelBuilder.Entity("MCBA_Web.Models.BillPay", b =>
                {
                    b.HasOne("MCBA_Web.Models.Account", "Account")
>>>>>>> dev
                        .WithMany()
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD
                    b.HasOne("MCBA_Admin.Models.Payee", "Payee")
=======
                    b.HasOne("MCBA_Web.Models.Payee", "Payee")
>>>>>>> dev
                        .WithMany()
                        .HasForeignKey("PayeeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Payee");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Login", b =>
                {
<<<<<<<< HEAD:Admin Web-API/Migrations/20230118054557_Models.Designer.cs
                    b.HasOne("MCBA_Admin.Models.Customer", "Customer")
                        .WithOne("Login")
                        .HasForeignKey("MCBA_Admin.Models.Login", "CustomerID")
========
                    b.HasOne("MCBA_Web.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
=======
            modelBuilder.Entity("MCBA_Web.Models.Login", b =>
                {
                    b.HasOne("MCBA_Web.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
>>>>>>> dev
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

<<<<<<< HEAD
<<<<<<<< HEAD:Admin Web-API/Migrations/20230118054557_Models.Designer.cs
            modelBuilder.Entity("MCBA_Admin.Models.Payee", b =>
                {
                    b.HasOne("MCBA_Admin.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MCBA_Admin.Models.Transaction", b =>
========
            modelBuilder.Entity("MCBA_Web.Models.Transaction", b =>
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
                {
                    b.HasOne("MCBA_Admin.Models.Account", "Account")
=======
            modelBuilder.Entity("MCBA_Web.Models.Transaction", b =>
                {
                    b.HasOne("MCBA_Web.Models.Account", "Account")
>>>>>>> dev
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCBA_Web.Models.Account", "DestinationAccount")
                        .WithMany()
                        .HasForeignKey("DestinationAccountNumber");

                    b.Navigation("Account");

                    b.Navigation("DestinationAccount");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Account", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Account", b =>
>>>>>>> dev
                {
                    b.Navigation("Transactions");
                });

<<<<<<< HEAD
            modelBuilder.Entity("MCBA_Admin.Models.Customer", b =>
=======
            modelBuilder.Entity("MCBA_Web.Models.Customer", b =>
>>>>>>> dev
                {
                    b.Navigation("Accounts");

                    b.Navigation("Address");
<<<<<<< HEAD
<<<<<<<< HEAD:Admin Web-API/Migrations/20230118054557_Models.Designer.cs

                    b.Navigation("Login");
========
>>>>>>>> dev:Customer Web/Migrations/20230120212116_Models.Designer.cs
=======
>>>>>>> dev
                });
#pragma warning restore 612, 618
        }
    }
}
